### ISSUE TITLE
Problems with manual installation

### ISSUE THREAD

**Issue by mmendesico** [magespecialist/m2-MSP_Notify#2]
How can I do the manual installation? I'm having problems and I'm not able to do the execution.

**Comment by giacmir** [comment]
Hello @mmendesico,
this module is not meant for manual installation. You can try by manually reviewing every and each composer dependency and by installing them one by one. In any case you must find a way to regenerate the composer autoloader or it won't work anyway.

Please note also that this module is abandoned and should only be used (with caution) for Magento versions not newer than 2.1.

If you are working with more recent version please refer to https://github.com/magespecialist/notifier-all (but that one cannot be installed manually either).
